# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[7,8], [9, 0], [1, 2]])
D = B + C
F = A.dot(D)
E = A.dot(B) + A.dot(C)
F == E #Proven

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) #3 columns for B's 3 rows
B = np.array([[1, 2], [3, 4], [5, 6]]) # 2 columns for C's 2 rows
C = np.array([[7,8], [9, 0]]) #2 rows

In [6]:
D = B.dot(C)
D

array([[25,  8],
       [57, 24],
       [89, 40]])

In [7]:
E = A.dot(D)
E

array([[ 406,  176],
       [ 919,  392],
       [1432,  608],
       [1945,  824]])

In [8]:
F = A.dot(B)
F

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

In [9]:
G = F.dot(C)

In [10]:
E == G # proven

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [11]:
C = A.dot(B)

In [12]:
D = B.dot(A)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

In [ ]:
#Not valid because B doesn't have right dimensions to take on A

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([[1, 2], [3, 4], [5, 6], [7,8]])

In [22]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
xt = x.transpose()
xt

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [19]:
z1 = xt.dot(y)
z1

array([[118, 140],
       [134, 160],
       [150, 180]])

In [20]:
yt = y.transpose()
yt

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [21]:
z2 = yt.dot(x)
z2

array([[118, 134, 150],
       [140, 160, 180]])

In [ ]:
#They're not equal yet - one is the transposition of the other. What does commutative mean?

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [26]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([[1, 2], [3, 4], [5, 6]])

In [27]:
z3 = x.dot(y)
z3

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

In [28]:
z3t = z3.transpose()
z3t #"(A.B)T"

array([[ 22,  49,  76, 103],
       [ 28,  64, 100, 136]])

In [30]:
yt = y.transpose()
yt

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
xt = x.transpose()
xt

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [32]:
z4 = yt.dot(xt)
z4

array([[ 22,  49,  76, 103],
       [ 28,  64, 100, 136]])

In [33]:
z3t == z4 #proven

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 